// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kobmhizkhczrqhhvcfgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvYm1oaXpraGN6cnFoaHZjZmdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDI4NzYsImV4cCI6MjA2NjcxODg3Nn0.Rym6Ny0meNK3LppQoxa_elo41CgyTcTJhGSzT8iR7Yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);